name: food_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  share: ^2.0.4
  flutter_card_swipper: ^0.4.0
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.20
  flutter_vector_icons: ^1.0.0
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  moor: ^4.6.1+1
  path_provider: ^2.0.9
  path: ^1.8.0
  sqlite3_flutter_libs: ^0.5.4
  dio: ^4.0.4
  shimmer: ^2.0.0
  rxdart: ^0.27.3
  google_maps_flutter: ^2.1.1
  flutter_credit_card: ^3.0.1
  flutterwave: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  moor_generator: ^4.6.0+1
  freezed: ^1.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

