import 'package:food_app/models/restaurant.dart';

class RestaurantDummy {
  static List<Restaurant> restaurantList = [
    Restaurant(
      section: 'Featured',
      name: 'German Doner Kehab',
      phone: '+123456789',
      email: 'example@email.com',
      notes:
          'All dishes may contain traces of the following allergens: Gluten, Crustaceans, Eggs, Fish, Peanuts, Soybeans, Milk, Nuts (e.g. almonds, hazelnuts, walnuts, cashews, pecan nuts, Brazil nuts, pistachio nuts, macadamia nuts), Celery, Mustard, Sesame, Sulphur dioxide/sulphites, Lupin, Molluscs. For any questions regarding the allergen contents of specific dishes please contact the restaurant directly.',
      rating: '4.5',
      noOfReviews: '500',
      deliveryTime: '15 - 25',
      address: '',
      orders: [],
      orderCategories: '',
      categories: '',
      images: [],
      distanceFromUserLocation: '',
    ),
    Restaurant(
      section: 'Featured',
      name: 'Saucy Chicks',
      phone: '+123456789',
      email: 'example@email.com',
      notes:
          'All dishes may contain traces of the following allergens: Gluten, Crustaceans, Eggs, Fish, Peanuts, Soybeans, Milk, Nuts (e.g. almonds, hazelnuts, walnuts, cashews, pecan nuts, Brazil nuts, pistachio nuts, macadamia nuts), Celery, Mustard, Sesame, Sulphur dioxide/sulphites, Lupin, Molluscs. For any questions regarding the allergen contents of specific dishes please contact the restaurant directly.',
      rating: '4.5',
      noOfReviews: '500',
      deliveryTime: '15 - 25',
      address: '',
      orders: [],
      orderCategories: '',
      categories: '',
      images: [],
      distanceFromUserLocation: '',
    ),
    Restaurant(
      section: 'Featured',
      name: 'Sainbury\'s',
      phone: '+123456789',
      email: 'example@email.com',
      notes:
          'All dishes may contain traces of the following allergens: Gluten, Crustaceans, Eggs, Fish, Peanuts, Soybeans, Milk, Nuts (e.g. almonds, hazelnuts, walnuts, cashews, pecan nuts, Brazil nuts, pistachio nuts, macadamia nuts), Celery, Mustard, Sesame, Sulphur dioxide/sulphites, Lupin, Molluscs. For any questions regarding the allergen contents of specific dishes please contact the restaurant directly.',
      rating: '4.5',
      noOfReviews: '500',
      deliveryTime: '15 - 25',
      address: '',
      orders: [],
      orderCategories: '',
      categories: '',
      images: [],
      distanceFromUserLocation: '',
    ), // end-of-bottom-part
    Restaurant(
      section: 'Featured',
      name: 'Rudy\'s Pizza',
      phone: '+123456789',
      email: 'example@email.com',
      notes:
          'All dishes may contain traces of the following allergens: Gluten, Crustaceans, Eggs, Fish, Peanuts, Soybeans, Milk, Nuts (e.g. almonds, hazelnuts, walnuts, cashews, pecan nuts, Brazil nuts, pistachio nuts, macadamia nuts), Celery, Mustard, Sesame, Sulphur dioxide/sulphites, Lupin, Molluscs. For any questions regarding the allergen contents of specific dishes please contact the restaurant directly.',
      rating: '4.5',
      noOfReviews: '500',
      deliveryTime: '15 - 25',
      address: '',
      orders: [],
      orderCategories: '',
      categories: '',
      images: [],
      distanceFromUserLocation: '',
    ),
    Restaurant(
      section: 'All',
      name: 'BB Bakery',
      phone: '+123456789',
      email: 'example@email.com',
      notes:
          'All dishes may contain traces of the following allergens: Gluten, Crustaceans, Eggs, Fish, Peanuts, Soybeans, Milk, Nuts (e.g. almonds, hazelnuts, walnuts, cashews, pecan nuts, Brazil nuts, pistachio nuts, macadamia nuts), Celery, Mustard, Sesame, Sulphur dioxide/sulphites, Lupin, Molluscs. For any questions regarding the allergen contents of specific dishes please contact the restaurant directly.',
      rating: '4.5',
      noOfReviews: '500',
      deliveryTime: '15 - 25',
      address: '',
      orders: [],
      orderCategories: '',
      categories: '',
      images: [],
      distanceFromUserLocation: '',
    ),
    Restaurant(
      section: 'All',
      name: 'Chicken Republic',
      phone: '+123456789',
      email: 'example@email.com',
      notes:
          'All dishes may contain traces of the following allergens: Gluten, Crustaceans, Eggs, Fish, Peanuts, Soybeans, Milk, Nuts (e.g. almonds, hazelnuts, walnuts, cashews, pecan nuts, Brazil nuts, pistachio nuts, macadamia nuts), Celery, Mustard, Sesame, Sulphur dioxide/sulphites, Lupin, Molluscs. For any questions regarding the allergen contents of specific dishes please contact the restaurant directly.',
      rating: '4.5',
      noOfReviews: '500',
      deliveryTime: '15 - 25',
      address: '',
      orders: [],
      orderCategories: '',
      categories: '',
      images: [],
      distanceFromUserLocation: '',
    ), // end-of-second-side-part
    Restaurant(
      section: 'All',
      name: 'Shoprite',
      phone: '+123456789',
      email: 'example@email.com',
      notes:
          'All dishes may contain traces of the following allergens: Gluten, Crustaceans, Eggs, Fish, Peanuts, Soybeans, Milk, Nuts (e.g. almonds, hazelnuts, walnuts, cashews, pecan nuts, Brazil nuts, pistachio nuts, macadamia nuts), Celery, Mustard, Sesame, Sulphur dioxide/sulphites, Lupin, Molluscs. For any questions regarding the allergen contents of specific dishes please contact the restaurant directly.',
      rating: '4.5',
      noOfReviews: '500',
      deliveryTime: '15 - 25',
      address: '',
      orders: [],
      orderCategories: '',
      categories: '',
      images: [],
      distanceFromUserLocation: '',
    ),
    Restaurant(
      section: 'All',
      name: 'YO!',
      phone: '+123456789',
      email: 'example@email.com',
      notes:
          'All dishes may contain traces of the following allergens: Gluten, Crustaceans, Eggs, Fish, Peanuts, Soybeans, Milk, Nuts (e.g. almonds, hazelnuts, walnuts, cashews, pecan nuts, Brazil nuts, pistachio nuts, macadamia nuts), Celery, Mustard, Sesame, Sulphur dioxide/sulphites, Lupin, Molluscs. For any questions regarding the allergen contents of specific dishes please contact the restaurant directly.',
      rating: '4.5',
      noOfReviews: '500',
      deliveryTime: '15 - 25',
      address: '',
      orders: [],
      orderCategories: '',
      categories: '',
      images: [],
      distanceFromUserLocation: '',
    ),
    Restaurant(
      section: 'All',
      name: 'Taco Bell',
      phone: '+123456789',
      email: 'example@email.com',
      notes:
          'All dishes may contain traces of the following allergens: Gluten, Crustaceans, Eggs, Fish, Peanuts, Soybeans, Milk, Nuts (e.g. almonds, hazelnuts, walnuts, cashews, pecan nuts, Brazil nuts, pistachio nuts, macadamia nuts), Celery, Mustard, Sesame, Sulphur dioxide/sulphites, Lupin, Molluscs. For any questions regarding the allergen contents of specific dishes please contact the restaurant directly.',
      rating: '4.5',
      noOfReviews: '500',
      deliveryTime: '15 - 25',
      address: '',
      orders: [],
      orderCategories: '',
      categories: '',
      images: [],
      distanceFromUserLocation: '',
    ), // end-of-top-part
    Restaurant(
      section: 'Top Rated',
      name: 'Burger King',
      phone: '+123456789',
      email: 'example@email.com',
      notes:
          'All dishes may contain traces of the following allergens: Gluten, Crustaceans, Eggs, Fish, Peanuts, Soybeans, Milk, Nuts (e.g. almonds, hazelnuts, walnuts, cashews, pecan nuts, Brazil nuts, pistachio nuts, macadamia nuts), Celery, Mustard, Sesame, Sulphur dioxide/sulphites, Lupin, Molluscs. For any questions regarding the allergen contents of specific dishes please contact the restaurant directly.',
      rating: '4.5',
      noOfReviews: '500',
      deliveryTime: '15 - 25',
      address: '',
      orders: [],
      orderCategories: '',
      categories: '',
      images: [],
      distanceFromUserLocation: '',
    ),
    Restaurant(
      section: 'Top Rated',
      name: 'PizzaExpress',
      phone: '+123456789',
      email: 'example@email.com',
      notes:
          'All dishes may contain traces of the following allergens: Gluten, Crustaceans, Eggs, Fish, Peanuts, Soybeans, Milk, Nuts (e.g. almonds, hazelnuts, walnuts, cashews, pecan nuts, Brazil nuts, pistachio nuts, macadamia nuts), Celery, Mustard, Sesame, Sulphur dioxide/sulphites, Lupin, Molluscs. For any questions regarding the allergen contents of specific dishes please contact the restaurant directly.',
      rating: '4.5',
      noOfReviews: '500',
      deliveryTime: '15 - 25',
      address: '',
      orders: [],
      orderCategories: '',
      categories: '',
      images: [],
      distanceFromUserLocation: '',
    ),
    Restaurant(
      section: 'Top Rated',
      name: 'Krispy Kreme',
      phone: '+123456789',
      email: 'example@email.com',
      notes:
          'All dishes may contain traces of the following allergens: Gluten, Crustaceans, Eggs, Fish, Peanuts, Soybeans, Milk, Nuts (e.g. almonds, hazelnuts, walnuts, cashews, pecan nuts, Brazil nuts, pistachio nuts, macadamia nuts), Celery, Mustard, Sesame, Sulphur dioxide/sulphites, Lupin, Molluscs. For any questions regarding the allergen contents of specific dishes please contact the restaurant directly.',
      rating: '4.5',
      noOfReviews: '500',
      deliveryTime: '15 - 25',
      address: '',
      orders: [],
      orderCategories: '',
      categories: '',
      images: [],
      distanceFromUserLocation: '',
    ),
    Restaurant(
      section: 'Top Rated',
      name: 'ALDI',
      phone: '+123456789',
      email: 'example@email.com',
      notes:
          'All dishes may contain traces of the following allergens: Gluten, Crustaceans, Eggs, Fish, Peanuts, Soybeans, Milk, Nuts (e.g. almonds, hazelnuts, walnuts, cashews, pecan nuts, Brazil nuts, pistachio nuts, macadamia nuts), Celery, Mustard, Sesame, Sulphur dioxide/sulphites, Lupin, Molluscs. For any questions regarding the allergen contents of specific dishes please contact the restaurant directly.',
      rating: '4.5',
      noOfReviews: '500',
      deliveryTime: '15 - 25',
      address: '',
      orders: [],
      orderCategories: '',
      categories: '',
      images: [],
      distanceFromUserLocation: '',
    ),
  ];
}
